### ISSUE TITLE
request: new policy profile for calling DBus method "requestSysState"

### ISSUE THREAD

**Issue by wdehoog** [ubports/apparmor-easyprof-ubuntu#10]
Can we have a new 'policy group' (or whatever it is called) to allow apps to call DBus method "requestSysState" on "com.canonical.powerd"?

I have an app that plays music and does not use the media-hub but another executable to actually play the audio (spotifyd). It needs to prevent the phone from suspending otherwise the audio becomes choppy.

Right now my app is unconfined so it can call "requestSysState" on "com.canonical.powerd". I think adding this new policy group would be a valuable feature for other apps as well. 

I do not now how these policy groups work but his file seems like a good starting point:
`/usr/share/apparmor/easyprof/policygroups/ubuntu/1.0/keep-display-on`

**Comment by wdehoog** [comment]
This seems to do the job. 

/usr/share/apparmor/easyprof/policygroups/ubuntu/1.0/hold_off_suspend (and the links)

```
# Description: Can request to hold off suspend
# Usage: common

# Allow communications with Unity screen API
dbus (send)
     bus=system
     interface="org.freedesktop.DBus.Introspectable"
     path="/com/canonical/powerd"
     member="Introspect"
     peer=(label=unconfined),
dbus (send)
     bus=system
     interface="com.canonical.powerd"
     path="/com/canonical/powerd"
     member="requestSysState"
     peer=(label=unconfined),
```

**Comment by gber** [comment]
Migrated to https://gitlab.com/ubports/development/core/apparmor-easyprof-ubuntu/-/issues/10.
