### ISSUE TITLE
request: new policy profile for becoming an Mpris2 player

### ISSUE THREAD

**Issue by wdehoog** [ubports/apparmor-easyprof-ubuntu#11]
Can we have a new 'policy group' (or whatever it is called) to allow apps to register itself as an Mpris2 compatible player?

I have an app that plays music and when it registers itself as an Mpris2 player it can be controlled using the media controls on the indicator panel.

Right now my app is unconfined so it can register itself as an Mpris2 player. I think adding this new policy group would be a valuable feature for other apps as well.

**Comment by wdehoog** [comment]
This seems to do the job.

/usr/share/apparmor/easyprof/policygroups/ubuntu/1.0/mpris2 (and the links)

```
# Description: Allowed to implement Mpris2
# Usage: common

dbus (send)
     bus=session
     interface=org.freedesktop.DBus
     path=/org/freedesktop/DBus
     member=RequestName
     peer=(label=unconfined),
dbus (bind)
     bus=session
     name=org.mpris.MediaPlayer2.@{APP_ID_DBUS},
dbus (receive, send)
     bus=session
     interface=org.mpris.MediaPlayer2
     path=/org/mpris/MediaPlayer2
     peer=(label=unconfined),
dbus (receive, send)
     bus=session
     interface=org.mpris.MediaPlayer2.Player
     path=/org/mpris/MediaPlayer2
     peer=(label=unconfined),
dbus (receive, send)
     bus=session
     path=/org/mpris/MediaPlayer2
     interface=org.freedesktop.DBus.Properties
     peer=(label=unconfined),

```

**Comment by gber** [comment]
Migrated to https://gitlab.com/ubports/development/core/apparmor-easyprof-ubuntu/-/issues/9.
