### ISSUE TITLE
Request: Allow netlink datagrams in networking (or connectivity?)

### ISSUE THREAD

**Issue by mzanetti** [ubports/apparmor-easyprof-ubuntu#12]
Trying to make nymea:app confined, I'm hitting a crash in avahi-client that it can't use netlink datagrams:

[  963.133342] [c4] type=1400 audit(1578747899.317:300): apparmor="DENIED" operation="create" profile="io.guh.nymeaapp_nymea-app_1.0.100" pid=7170 comm="nymea-app" family="netlink" sock_type="dgram" protocol=0

It works fine if I change the policy (/usr/share/apparmor/easyprof/policygroups/ubuntu/1.0/networking) to include `network netlink dgram,` 

Now tbh I'm not 100% sure what else this implies in detail and how big the hole in the policy actually is, but given the exact same code is working fine on Android with the default "networking" policy I'm assuming it shouldn't be that bad... Still needs to be investigated.

**Comment by dobey** [comment]
This was fixed by https://github.com/ubports/apparmor-easyprof-ubuntu/commit/b620ba8853f664354b1cf6d0ced474a51cdb8c81 which is included in OTA-16.
