### ISSUE TITLE
Request: New policy profile for XMir applications

### ISSUE THREAD

**Issue by Elleo** [ubports/apparmor-easyprof-ubuntu#16]
Currently applications that require the `X-Ubuntu-XMir-Enable=true` setting in their .desktop file are unable to launch within confinement. Permission is deined to exec xmir-helper, preventing the application from launching, e.g.:

```** (process:1595): WARNING **: Unable to exec '/usr/lib/arm-linux-gnueabihf/ubuntu-app-launch/xmir-helper javatest.comlarsic_JavaTest_1.2.0 JavaBin/bin/java main' in '/opt/click.ubuntu.com/.click/users/phablet/javatest.comlarsic': Permission denied```

As far as I can tell applications using `X-Ubuntu-XMir-Enable=true` can currently only be made to work by using an unconfined AppArmor policy.

Reference: https://forums.ubports.com/topic/4132/getting-java-working-on-ubtouch/13

**Comment by dekkerj1** [comment]
Hello Elleo, will you please explain to me how to set an unconfined AppArmor policy?

**Comment by Elleo** [comment]
Just set `"template": "unconfined"` in your app's apparmor file

**Comment by Elleo** [comment]
For example a complete unconfined apparmor policy file would look like:
`{
    "template": "unconfined",
    "policy_version": 16.04
}`

**Comment by dekkerj1** [comment]
> For example a complete unconfined apparmor policy file would look like:
> `{ "template": "unconfined", "policy_version": 16.04 }`



> Just set `"template": "unconfined"` in your app's apparmor file

Thank you,

**Comment by gber** [comment]
Migrated to https://gitlab.com/ubports/development/core/apparmor-easyprof-ubuntu/-/issues/8.
