### ISSUE TITLE
apparmor issues with webapps and qtwebengine

### ISSUE THREAD

**Issue by luksus42** [ubports/apparmor-easyprof-ubuntu#7]
For documentation purpose: 
@UniversalSuperBox feel free to move or do something else with it.

With the change to qtwebengine, there  appeared some problems with apparmor rights regarding html5-apps.
See the log:
https://paste.ubuntu.com/p/zwhmCqZZnC/

This may cause the issue, that the javascript "local-storage" is not accessable, which means that app-settings are not stored, which rely on the local-storage.

**Comment by mariogrip** [comment]
Fixed by: https://github.com/ubports/morph-browser/commit/02fffeb661abb13d3f5c7d5f1559e3790b1fd1a0
